obj = main.obj
bin = spcbrd.exe

CC=wcc386
CFLAGS=-oneatx -zp4 -fpi87 -fp5 -bt=dos -za99 -zq -ivendor\include
LD=wlink

default: clean $(bin)

$(bin): $(obj)
	$(LD) system dos4g option caseexact name $@ file { $(obj) } library vendor\lib\MIDAS.LIB

.c.obj:
	$(CC) -fo=$@ $(CFLAGS) $<

clean: .symbolic
	del *.obj
	del $(bin)
